# Generated by Django 3.2 on 2021-05-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('enum', models.IntegerField(unique=True)),
                ('esal', models.FloatField()),
            ],
        ),
    ]
